Feature/api setup
projectx-curtains/API_CURTAINS pull request #1
Opened 2022-08-30 14:40 UTC by zd-prog

2022-08-30 15:07 UTC, C0Rs1K approved these changes
Great job!!

2022-08-31 07:21 UTC, EgorAntonovich commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BE] API setup](https://trello.com/c/ZymKwbzn/48-be-api-setup)

2022-08-31 09:52 UTC, EgorAntonovich requested changes

2022-08-31 09:52 UTC, EgorAntonovich commented on Curtains/Curtains.Application/Class1.cs
> +    public class Class1
What is it "Class1"?

2022-08-31 09:52 UTC, EgorAntonovich commented on Curtains/Curtains.Application_tests/UnitTest1.cs
> +namespace Curtains.Application_tests
Please change naming to Curtains.Application.Tests
Also move all tests projects to separated folder with naming Tests

2022-08-31 09:52 UTC, EgorAntonovich commented on Curtains/Curtains.Application_tests/Usings.cs
> +global using NUnit.Framework;
What is it the class?

2022-08-31 09:52 UTC, EgorAntonovich commented on Curtains/Curtains.Domain/Class1.cs
> +    public class Class1
The same

2022-08-31 09:52 UTC, EgorAntonovich commented on Curtains/Curtains.Domain_tests/UnitTest1.cs
> +namespace Curtains.Domain_tests
The same as Application

2022-08-31 09:52 UTC, EgorAntonovich commented on Curtains/Curtains.Infrastructure/Class1.cs
> +    public class Class1
??

2022-08-31 10:05 UTC, zd-prog commented on Curtains/Curtains.Application_tests/Usings.cs
> +global using NUnit.Framework;
This class was created automaticaly.

2022-08-31 10:18 UTC, EgorAntonovich approved these changes
Looks good for me

2022-08-31 10:18 UTC, merged