fix
projectx-curtains/API_CURTAINS pull request #21
Opened 2022-11-22 11:44 UTC by zd-prog

2022-11-22 12:14 UTC, EgorAntonovich requested changes

2022-11-22 12:14 UTC, EgorAntonovich commented on Curtains/Curtains.Api/log.txt
> +2022-11-22 14:33:08.524 +03:00 [INF] Application Start
What the log file in PR?

2022-11-23 12:12 UTC, zd-prog commented on Curtains/Curtains.Api/log.txt
> +2022-11-22 14:33:08.524 +03:00 [INF] Application Start
Removed

2022-11-25 00:16 UTC, EgorAntonovich approved these changes

2022-11-25 06:48 UTC, merged