Hotfix/add migration
projectx-curtains/API_CURTAINS pull request #3
Opened 2022-09-06 16:18 UTC by C0Rs1K

Changed incorrect usings to correct and changed namespace in curtains context

2022-09-07 06:40 UTC, zd-prog requested changes

2022-09-07 06:40 UTC, zd-prog commented on Curtains/Curtains.Infrastructure/Migrations/CurtainsContextModelSnapshot.cs
> +using Curtains.Domain.Data;
The name of namespace should be Curtains.Domain.Models

2022-09-07 06:40 UTC, zd-prog commented on Curtains/Curtains.Infrastructure/Migrations/20220901113709_InitCreate.Designer.cs
> +using Curtains.Domain.Data;
The name of namespace should be Curtains.Domain.Models

2022-09-07 06:44 UTC, zd-prog approved these changes

2022-09-07 22:45 UTC, EgorAntonovich approved these changes
Approved

2022-09-08 13:20 UTC, merged

2022-09-08 15:02 UTC, C0Rs1K commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BE] E-1 S-1 T-3 DB creation](https://trello.com/c/ioMnVGc3/47-be-e-1-s-1-t-3-db-creation)

2022-09-08 15:02 UTC, C0Rs1K commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BE] E-1 S-1 T-6 Create EF layer for connection between API & DB](https://trello.com/c/F1wpmUz4/49-be-e-1-s-1-t-6-create-ef-layer-for-connection-between-api-db)