Feature/change dto
projectx-curtains/API_CURTAINS pull request #35
Opened 2023-02-13 14:14 UTC by C0Rs1K

2023-02-15 07:20 UTC, zd-prog requested changes
Check nullable fields, please

2023-02-15 07:20 UTC, zd-prog commented on Curtains/Curtains.Application/DTO/BedspreadsDTO.cs
> +        public BedspreadsSizeDTO Size { get; set; }
Why id is nullable, when Size model is not nullable?

2023-02-15 07:20 UTC, zd-prog commented on Curtains/Curtains.Application/DTO/CurtainsDTO.cs
> +        public int? MaterialId { get; set; }
Why this fields are nullable?

2023-02-15 07:20 UTC, zd-prog commented on Curtains/Curtains.Application/DTO/CurtainsDTO.cs
> +        public int? CurtainsKindId { get; set; }
same

2023-02-16 13:50 UTC, zd-prog approved these changes

2023-02-23 14:51 UTC, EgorAntonovich approved these changes

2023-02-27 18:24 UTC, merged