Feature/Add db table for customer reviews
projectx-curtains/API_CURTAINS pull request #4
Opened 2022-09-07 15:20 UTC by Pilyut

Added ReviewModel, ReviewMapping and Migration

2022-09-07 22:50 UTC, EgorAntonovich requested changes

2022-09-07 22:50 UTC, EgorAntonovich commented on Curtains/Curtains.Domain/Data/Mappings/ReviewMapping.cs
> +                .UseCollation("SQL_Latin1_General_CP1_CI_AS");
How we can simplify using same collations instead of using it in every property?

2022-09-07 22:50 UTC, EgorAntonovich commented on Curtains/Curtains.Domain/Data/Mappings/ReviewMapping.cs
> +                .UseCollation("SQL_Latin1_General_CP1_CI_AS");
May be it's make sense to move it into appsettings.json
Or we can create constants static class and use them from it.

2022-09-08 13:38 UTC, C0Rs1K requested changes

2022-09-08 13:38 UTC, C0Rs1K commented on Curtains/Curtains.Domain/Data/Mappings/ReviewMapping.cs
> +namespace Curtains.Domain.Models
I guess mappings should be in Curtains.Domain.Data namespace

2022-09-13 12:45 UTC, C0Rs1K requested changes
Look's good :) just rename some namespaces

2022-09-13 12:45 UTC, C0Rs1K commented on Curtains/Curtains.Domain/Data/Mappings/ReviewMapping.cs
> +namespace Curtains.Domain.Models
We still need change mapping's namespaces from Curtains.Domain.Models to Curtains.Domain.Data

2022-09-13 12:45 UTC, C0Rs1K commented on Curtains/Curtains.Infrastructure/Migrations/CurtainsContextModelSnapshot.cs
> +namespace Curtains.Domain.Migrations
this namespace is probably Curtains.Infrastructure.Migrations

2022-09-13 12:46 UTC, C0Rs1K commented on Curtains/Curtains.Domain/Data/Mappings/ReviewMapping.cs
> +namespace Curtains.Domain.Models
Not just ReveiwMapping but all of them)

2022-09-13 19:57 UTC, C0Rs1K approved these changes
Great!

2022-09-27 14:50 UTC, EgorAntonovich commented
Please rewrite this according to new branch policy

2022-09-27 15:07 UTC, closed without merging